# ckpt/config options(static)
blip_path: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large.pth
med_config: src/config/med_config.json

# ckpt/logger options(dynamic)
checkpoint_base: checkpoint
visual_base: visualization
log_base: log

# dataset
data_base: /projects/brl/mobility/imagereward/ImageRewardDB
image_base: /projects/brl/mobility/imagereward/ImageRewardDB
pair_store_base: /projects/brl/mobility/blip_train


# model parameters
BLIP:
  # size of vit model; base or large
  vit: 'large'
  image_size: 224

ImageReward:
  mlp_dim: 768
